# Generated by Django 4.0.3 on 2022-03-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Add Snippet here', max_length=200),
        ),
    ]
