# Generated by Django 4.0.3 on 2022-03-08 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2022, 3, 8)),
            preserve_default=False,
        ),
    ]
