# Generated by Django 4.0.3 on 2022-03-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_author_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
